### ISSUE TITLE
Popover first opens arrow bad position with changeDetection: ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by kevinLourencoDev** [material-extended/popover#57]
#### Bug :

When we **first opens the popover**, the arrow is not good positionned. We already facing this kind of issue here : #28 
The bug have been fixed with a good utilisation of zone due to @kostia-lev

But in an application that use  changeDetection: ChangeDetectionStrategy.OnPush the bug occur again : 

![bug-popover-arrow](https://user-images.githubusercontent.com/45124458/61379248-76f0ad00-a8a7-11e9-8c75-08fd9e48c908.gif)

#### What are the steps to reproduce?

You have to try to implemante an popover with hover trigger. 

Put  changeDetection: ChangeDetectionStrategy.OnPush directly on component decoration : 

`
import { Component, HostBinding, ChangeDetectionStrategy } from '@angular/core';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
`
#### Why using ChangeDetectionStrategy ?

Angular is know to check always all the componant in order to detect change. This occure for the single small change on an object. Is very expensif in big application.

With OnPush strategy, you say to angular to only update if the entire object change like in functionnal programming. This force you to use only immutable object as a best practice. Is a very big win of performance. See more : [https://netbasal.com/a-comprehensive-guide-to-angular-onpush-change-detection-strategy-5bac493074a4](https://netbasal.com/a-comprehensive-guide-to-angular-onpush-change-detection-strategy-5bac493074a4)

#### Way to resolve this issue

Create immutable objet for popover and change it as functionnal programming at the beginning. Actually, this work at the second time we hover at the trigger, so that meen that is already the case. We juste have to do the same for the first generation.

I hope @joejordanbrown it's clear and it will be a quick fix.

**Comment by joejordanbrown** [comment]
@kevinLourencoDev 

Thanks for your detailed bug report.

I will look into this when I have time, but I can't guarantee that will be this week, I'm currently very busy.

You are welcome to create a pull request if this is urgent for you.

**Comment by joejordanbrown** [comment]
@kevinLourencoDev 

Good news I managed to find a little bit of time to fix this today.

I've just pushed the changes to NPM [@material-extended/mde@^2.3.1](https://www.npmjs.com/package/@material-extended/mde).

**With fix:**
https://stackblitz.com/edit/angular-popover-onpush-demo

**Without fix:**
https://stackblitz.com/edit/angular-popover-onpush-broken

Let me know if you have any issues.

**Comment by kevinLourencoDev** [comment]
@joejordanbrown 

Thanks you a lot, it's perfect now !
